apiVersion: v2
name: onecx-service-auth-bff
version: 0.0.0
appVersion: 0.0.0
description: Onecx service auth bff
keywords:
  - example
sources:
  - https://github.com/onecx/onecx-service-auth-bff
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: 0.42.0
    repository: oci://ghcr.io/onecx/charts